"""Writes do/labels.do (variable labels, value labels, notes, variable order) from questionnaire/dictionary.py."""
import os, re, sys, textwrap
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "questionnaire"))
from dictionary import ROWS, LSETS, MODULES

MODNAME = {m[0]: m[1] for m in MODULES}; MODNAME["X"] = "Constructed variables (built in Stata from the asked variables)"; MODNAME["Z"] = "Synthetic-design variables (not collected)"

def clean(s):
    return re.sub(r"\s+", " ", str(s).replace('"', "'").replace("`", "'").replace("$", "S")).strip()

def notes(var, tag, text):
    out = []
    parts = textwrap.wrap(clean(text), 230)
    for i, p in enumerate(parts):
        out.append(f'notes {var}: {tag if i == 0 else tag + " (cont.)"}: {p}')
    return out

L = ["* AUTO-GENERATED by do/make_labels_do.py from questionnaire/dictionary.py -- do not edit by hand.",
     "* Applies value labels, variable labels, notes and variable order to the final dataset.", ""]
used = sorted({r["lset"] for r in ROWS if r["lset"]})
for s in used:
    L.append("label define " + s + " " + " ".join(f'{k} "{clean(v)}"' for k, v in LSETS[s].items()) + ", replace")
L.append("")
# Synthetic-only variables exist in the generated pool but NEVER in real field data, whether that
# comes from Kobo or from the web form. Labelling them unconditionally made the build fail
# outright on any real export, so their label/notes lines get a "capture" prefix: Stata then
# silently skips them when absent, and the one do-file serves both synthetic and real data.
SYNTH = {r["name"] for r in ROWS if r["origin"] == "synthetic"}
cap = lambda n: "capture " if n in SYNTH else ""
for r in ROWS:
    L.append(cap(r['name']) + f'label variable {r["name"]} "{clean(r["label"])}"')
    # A select_multiple carries an lset so the PDF and the XLSForm can print its choices, but Stata
    # imports it as the raw space-separated string -- and you may not attach a value label to a
    # string. The per-choice binaries the build splits out (other_act_1..13) carry the labels instead.
    if r["lset"] and r["kind"] != "multi":
        L.append(cap(r['name']) + f'label values {r["name"]} {r["lset"]}')
L.append("")
# Synthetic-only variables exist in the generated pool but NEVER in real field data, whether that
# comes from Kobo or from the web form. Labelling them unconditionally made the build fail
# outright on any real export, so their label/notes lines get a "capture" prefix: Stata then
# silently skips them when absent, and the one do-file serves both synthetic and real data.
SYNTH = {r["name"] for r in ROWS if r["origin"] == "synthetic"}
cap = lambda n: "capture " if n in SYNTH else ""
for r in ROWS:
    v = r["name"]
    L.append(cap(v) + f'notes {v}: Module {r["module"]} - {clean(MODNAME[r["module"]])}; origin: {r["origin"]}')
    L += [cap(v) + x for x in notes(v, "Meaning", r["desc"])]
    if r["origin"] == "constructed":
        L += [cap(v) + x for x in notes(v, "Formula", r["formula"])]
    elif r["origin"] == "asked":
        L += [cap(v) + x for x in notes(v, "Question", r["question"])]
    if r["skip"]:
        L += [cap(v) + x for x in notes(v, "Skip rule", r["skip"])]
    L += [cap(v) + x for x in notes(v, "Source", r["source"])]
L.append("")
L.append("order " + " ".join(r["name"] for r in ROWS if r["origin"] != "synthetic"))
for _s in sorted(SYNTH): L.append(f"capture order {_s}, last")
L.append('label data "Kedarnath Yatra workers - worked example (SYNTHETIC), final instrument v2"')
L.append("note: SYNTHETIC worked example built from the final questionnaire and variable list. Nothing here is a finding about real workers.")
open(os.path.join(HERE, "labels.do"), "w", encoding="utf-8").write("\n".join(L) + "\n")
print("labels.do written:", len(L), "lines;", len(ROWS), "variables;", len(used), "value-label sets")
